In [47]:
import polars as pl

In [48]:
#Load df
df = pl.read_csv("../data/output/v2/2.clean_df_v2.csv")

df = df.rename({
    "Start date": "start_date",
    "Start station number": "start_station",
    "End date": "end_date",
    "End station number": "end_station",
    "Total duration (ms)": "duration_ms",
    "Operating date": "operating_date",
    "Day of week": "day_of_week",
    "Hour of day": "hour"
})

df = df.with_columns([
    pl.col("start_date").str.to_datetime(strict=False),
    pl.col("end_date").str.to_datetime(strict=False),
    pl.col("operating_date").str.to_date(strict=False),
])
df

shape: (8_762_355, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ start_dat ┆ start_sta ┆ end_date  ┆ end_stati ┆ … ┆ start_sta ┆ end_stati ┆ end_stati ┆ end_stat │
│ e         ┆ tion      ┆ ---       ┆ on        ┆   ┆ tion_name ┆ on_latitu ┆ on_longit ┆ ion_name │
│ ---       ┆ ---       ┆ datetime[ ┆ ---       ┆   ┆ ---       ┆ de        ┆ ude       ┆ ---      │
│ datetime[ ┆ i64       ┆ μs]       ┆ i64       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-01-1 ┆ 1043      ┆ 2025-01-1 ┆ 200149    ┆ … ┆ Museum of ┆ 51.511542 ┆ -0.056667 ┆ Watney   │
│ 4         ┆           ┆ 5         ┆           ┆   ┆ London,   ┆           ┆           ┆ Street,  │
│ 23:59:00  ┆           ┆ 00:13:00  ┆           ┆   ┆ Barbican  ┆           ┆           ┆ Shadwell │
│ 2025-01-1 ┆ 300015    ┆ 2025-01-1 ┆ 300229    ┆ … ┆ Binfield  ┆ 51.469202 ┆ -0.119022 ┆ Sidney   │
│ 4         ┆           ┆ 5         ┆           ┆   ┆ Road,     ┆           ┆           ┆ Road,    │
│ 23:59:00  ┆           ┆ 00:04:00  ┆           ┆   ┆ Stockwell ┆           ┆           ┆ Stockwel │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ l        │
│ 2025-01-1 ┆ 1068      ┆ 2025-01-1 ┆ 1051      ┆ … ┆ Norton    ┆ 51.534042 ┆ -0.086379 ┆ Shoredit │
│ 4         ┆           ┆ 5         ┆           ┆   ┆ Folgate,  ┆           ┆           ┆ ch Park, │
│ 23:59:00  ┆           ┆ 00:10:00  ┆           ┆   ┆ Liverpool ┆           ┆           ┆ Hoxton   │
│           ┆           ┆           ┆           ┆   ┆ Stre…     ┆           ┆           ┆          │
│ 2025-01-1 ┆ 1159      ┆ 2025-01-1 ┆ 1007      ┆ … ┆ Berry     ┆ 51.51477  ┆ -0.122219 ┆ Drury    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆ Street,   ┆           ┆           ┆ Lane,    │
│ 23:59:00  ┆           ┆ 00:10:00  ┆           ┆   ┆ Clerkenwe ┆           ┆           ┆ Covent   │
│           ┆           ┆           ┆           ┆   ┆ ll        ┆           ┆           ┆ Garden   │
│ 2025-01-1 ┆ 200048    ┆ 2025-01-1 ┆ 1058      ┆ … ┆ Page      ┆ 51.510212 ┆ 0.004979  ┆ Orchard  │
│ 4         ┆           ┆ 5         ┆           ┆   ┆ Street,   ┆           ┆           ┆ Place,   │
│ 23:58:00  ┆           ┆ 00:14:00  ┆           ┆   ┆ Westminst ┆           ┆           ┆ Blackwal │
│           ┆           ┆           ┆           ┆   ┆ er        ┆           ┆           ┆ l Tunne… │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-12-1 ┆ 200141    ┆ 2025-12-1 ┆ 200237    ┆ … ┆ Westfield ┆ 51.472817 ┆ -0.199783 ┆ Parson's │
│ 6         ┆           ┆ 6         ┆           ┆   ┆ Ariel     ┆           ┆           ┆ Green ,  │
│ 00:02:00  ┆           ┆ 00:16:00  ┆           ┆   ┆ Way,      ┆           ┆           ┆ Parson's │
│           ┆           ┆           ┆           ┆   ┆ White     ┆           ┆           ┆ Gree…    │
│           ┆           ┆           ┆           ┆   ┆ Cit…      ┆           ┆           ┆          │
│ 2025-12-1 ┆ 200011    ┆ 2025-12-1 ┆ 200250    ┆ … ┆ Furze     ┆ 51.520893 ┆ -0.051394 ┆ Clevelan │
│ 6         ┆           ┆ 6         ┆           ┆   ┆ Green,    ┆           ┆           ┆ d Way,   │
│ 00:01:00  ┆           ┆ 00:16:00  ┆           ┆   ┆ Bow       ┆           ┆           ┆ Stepney  │
│ 2025-12-1 ┆ 300096    ┆ 2025-12-1 ┆ 962       ┆ … ┆ Tallis    ┆ 51.505569 ┆ -0.111606 ┆ Stamford │
│ 6         ┆           ┆ 6         ┆           ┆   ┆ Street,   ┆           ┆           ┆ Street,  │
│ 00:00:00  ┆           ┆ 00:07:00  ┆           ┆   ┆ Temple    ┆           ┆           ┆ South    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Bank     │
│ 2025-12-1 ┆ 3495      ┆ 2025-12-1 ┆ 300207    ┆ … ┆ Wells     ┆ 51.464995 ┆ -0.130908 ┆ Gauden   │
│ 6         ┆           ┆ 6         ┆           ┆   ┆ Street,   ┆           ┆           ┆ Road,    │
│ 00:00:00  ┆           ┆ 00:24:00  ┆           ┆   ┆ Fitzrovia ┆           ┆           ┆ Clapham  │
│ 2025-12-1 ┆ 200185    ┆ 2025-12-1 ┆ 300013    ┆ … ┆ St.       ┆ 51.474376 ┆ -0.155442 ┆ Austin   │
│ 6         ┆           ┆ 6         ┆           ┆   ┆ John's    ┆           ┆           ┆ Road,    │
│ 00:00:00  ┆           ┆ 00:08:00  ┆           ┆   ┆ Road,     ┆           ┆           ┆ Batterse │
│           ┆           ┆           ┆           ┆   ┆ Clapham   ┆           ┆           ┆ a Park   │
│           ┆           ┆           ┆           ┆   ┆ Junct…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [49]:
#########################
#Create station profiles
#########################

#-------------------
#departure features
#-------------------
departures = (
    df
    .group_by("start_station")
    .agg([
        pl.len().alias("n_departures"), #number of trips starting at this station

        pl.col("duration_ms").mean().alias("mean_duration"), #average trip duration for trips departing from that station.
        pl.col("duration_ms").median().alias("median_duration"), #median trip duration departing from that station.
        pl.col("duration_ms").std().alias("std_duration"), #standard deviation trip duration departing from that station.

        pl.col("end_station").n_unique().alias("n_destinations"), #Counts the number of different destination stations reached from each starting station.
    ])
    .rename({"start_station": "station"})
)


#--------------------
#arrival features
#--------------------
arrivals = (
    df
    .group_by("end_station")
    .agg([
        pl.len().alias("n_arrivals"), #number of trips arriving at this station

        pl.col("start_station").n_unique().alias("n_origins"), #Counts the number of different destination stations that end in each end station.
    ])
    .rename({"end_station": "station"})
)


#Join them
stations = departures.join(
    arrivals,
    on="station",
    how="full"
).fill_null(0)

stations

shape: (822, 9)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ station ┆ n_departur ┆ mean_dura ┆ median_du ┆ … ┆ n_destina ┆ station_r ┆ n_arrival ┆ n_origins │
│ ---     ┆ es         ┆ tion      ┆ ration    ┆   ┆ tions     ┆ ight      ┆ s         ┆ ---       │
│ i64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ u32       │
│         ┆ u32        ┆ f64       ┆ f64       ┆   ┆ u32       ┆ i64       ┆ u32       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10632   ┆ 4058       ┆ 1.2457e6  ┆ 880538.5  ┆ … ┆ 452       ┆ 10632     ┆ 4031      ┆ 439       │
│ 22169   ┆ 11770      ┆ 905153.13 ┆ 542541.0  ┆ … ┆ 615       ┆ 22169     ┆ 11779     ┆ 618       │
│         ┆            ┆ 8233      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 200053  ┆ 3280       ┆ 2.1102e6  ┆ 925209.5  ┆ … ┆ 466       ┆ 200053    ┆ 3097      ┆ 426       │
│ 300048  ┆ 7946       ┆ 1.0453e6  ┆ 742999.5  ┆ … ┆ 374       ┆ 300048    ┆ 7796      ┆ 409       │
│ 22175   ┆ 6259       ┆ 1.5980e6  ┆ 889888.0  ┆ … ┆ 393       ┆ 22175     ┆ 6160      ┆ 406       │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1045    ┆ 9855       ┆ 1.2386e6  ┆ 761825.0  ┆ … ┆ 655       ┆ 1045      ┆ 9912      ┆ 645       │
│ 1179    ┆ 7539       ┆ 1.0254e6  ┆ 763257.0  ┆ … ┆ 542       ┆ 1179      ┆ 7534      ┆ 533       │
│ 200157  ┆ 14369      ┆ 1.0581e6  ┆ 743040.0  ┆ … ┆ 646       ┆ 200157    ┆ 14398     ┆ 661       │
│ 200127  ┆ 4970       ┆ 1.8336e6  ┆ 965054.5  ┆ … ┆ 379       ┆ 200127    ┆ 5497      ┆ 420       │
│ 200154  ┆ 6182       ┆ 1.7225e6  ┆ 730145.5  ┆ … ┆ 485       ┆ 200154    ┆ 6308      ┆ 524       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [50]:
#-------------------
#departure/arrival ratio
#-------------------

stations = stations.with_columns(
    (pl.col('n_departures')/pl.col('n_arrivals')).alias('departure_arrival_ratio')
)

stations

shape: (822, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ station ┆ n_departur ┆ mean_dura ┆ median_du ┆ … ┆ station_r ┆ n_arrival ┆ n_origins ┆ departure │
│ ---     ┆ es         ┆ tion      ┆ ration    ┆   ┆ ight      ┆ s         ┆ ---       ┆ _arrival_ │
│ i64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ ratio     │
│         ┆ u32        ┆ f64       ┆ f64       ┆   ┆ i64       ┆ u32       ┆           ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10632   ┆ 4058       ┆ 1.2457e6  ┆ 880538.5  ┆ … ┆ 10632     ┆ 4031      ┆ 439       ┆ 1.006698  │
│ 22169   ┆ 11770      ┆ 905153.13 ┆ 542541.0  ┆ … ┆ 22169     ┆ 11779     ┆ 618       ┆ 0.999236  │
│         ┆            ┆ 8233      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 200053  ┆ 3280       ┆ 2.1102e6  ┆ 925209.5  ┆ … ┆ 200053    ┆ 3097      ┆ 426       ┆ 1.059089  │
│ 300048  ┆ 7946       ┆ 1.0453e6  ┆ 742999.5  ┆ … ┆ 300048    ┆ 7796      ┆ 409       ┆ 1.019241  │
│ 22175   ┆ 6259       ┆ 1.5980e6  ┆ 889888.0  ┆ … ┆ 22175     ┆ 6160      ┆ 406       ┆ 1.016071  │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1045    ┆ 9855       ┆ 1.2386e6  ┆ 761825.0  ┆ … ┆ 1045      ┆ 9912      ┆ 645       ┆ 0.994249  │
│ 1179    ┆ 7539       ┆ 1.0254e6  ┆ 763257.0  ┆ … ┆ 1179      ┆ 7534      ┆ 533       ┆ 1.000664  │
│ 200157  ┆ 14369      ┆ 1.0581e6  ┆ 743040.0  ┆ … ┆ 200157    ┆ 14398     ┆ 661       ┆ 0.997986  │
│ 200127  ┆ 4970       ┆ 1.8336e6  ┆ 965054.5  ┆ … ┆ 200127    ┆ 5497      ┆ 420       ┆ 0.90413   │
│ 200154  ┆ 6182       ┆ 1.7225e6  ┆ 730145.5  ┆ … ┆ 200154    ┆ 6308      ┆ 524       ┆ 0.980025  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [51]:
#-------------------
#Avg departures and arrivals per day
#-------------------
daily_departures = (
    df
    .group_by(["operating_date", "start_station"])
    .agg(
        pl.len().alias("departures")
    )
)

daily_arrivals = (
    df
    .group_by(["operating_date", "end_station"])
    .agg(
        pl.len().alias("arrivals")
    )
)

avg_departures = (
    daily_departures
    .group_by("start_station")
    .agg(
        pl.col("departures").mean().alias("avg_daily_departures")
    )
    .rename({"start_station": "station"})
)

avg_arrivals = (
    daily_arrivals
    .group_by("end_station")
    .agg(
        pl.col("arrivals").mean().alias("avg_daily_arrivals")
    )
    .rename({"end_station": "station"})
)

station_daily_avg = (
    avg_departures
    .join(avg_arrivals, on="station", how="left")
    .sort("station")
)

station_daily_avg

shape: (820, 3)
┌────────────┬──────────────────────┬────────────────────┐
│ station    ┆ avg_daily_departures ┆ avg_daily_arrivals │
│ ---        ┆ ---                  ┆ ---                │
│ i64        ┆ f64                  ┆ f64                │
╞════════════╪══════════════════════╪════════════════════╡
│ 959        ┆ 25.78022             ┆ 26.406593          │
│ 960        ┆ 100.381868           ┆ 121.17033          │
│ 961        ┆ 28.717033            ┆ 28.89011           │
│ 962        ┆ 30.870523            ┆ 32.909091          │
│ 963        ┆ 33.346154            ┆ 38.635616          │
│ …          ┆ …                    ┆ …                  │
│ 200191444  ┆ 9.115385             ┆ 9.192308           │
│ 200230444  ┆ 58.301075            ┆ 56.308511          │
│ 300032444  ┆ 26.478261            ┆ 25.73913           │
│ 300241444  ┆ 38.451613            ┆ 37.290323          │
│ 2001454444 ┆ 19.946108            ┆ 19.502994          │
└────────────┴──────────────────────┴────────────────────┘

In [52]:
#----------------
#add departures per hour
#----------------

# hour_profile = (
#     df
#     .group_by(["start_station", "hour"])
#     .agg(
#         pl.len().alias("count")
#     )
# )


# hour_profile = (
#     hour_profile
#     .pivot(
#         on="hour",
#         index="start_station",
#         values="count"
#     )
#     .fill_null(0)
# )


# hour_profile = hour_profile.rename({
#     "start_station": "station"
# })

# hour_profile

In [53]:
#--------------------
# Normalize hourly profile
#--------------------

# hour_columns = [str(i) for i in range(24) if str(i) in hour_profile.columns]

# hour_profile = hour_profile.with_columns(
#     [
#         (pl.col(c) / pl.sum_horizontal(hour_columns)).alias(f"{c}_hours")
#         for c in hour_columns
#     ]
# ).drop(hour_columns)

# hour_profile

In [54]:
#-----------------------
#Weekend and weekday behavior
#-----------------------
print(
    df
    .select("day_of_week")
    .unique()
    .sort("day_of_week")
)

df = df.with_columns(
    (pl.col("day_of_week") >= 6).alias("is_weekend")
)

print(df)

weekend_profile = (
    df
    .group_by("start_station")
    .agg([
        pl.col("is_weekend").mean().alias("weekend_ratio")
    ])
    .rename({"start_station": "station"})
)

weekend_profile

shape: (7, 1)
┌─────────────┐
│ day_of_week │
│ ---         │
│ i64         │
╞═════════════╡
│ 1           │
│ 2           │
│ 3           │
│ 4           │
│ 5           │
│ 6           │
│ 7           │
└─────────────┘
shape: (8_762_355, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ start_dat ┆ start_sta ┆ end_date  ┆ end_stati ┆ … ┆ end_stati ┆ end_stati ┆ end_stati ┆ is_weeke │
│ e         ┆ tion      ┆ ---       ┆ on        ┆   ┆ on_latitu ┆ on_longit ┆ on_name   ┆ nd       │
│ ---       ┆ ---       ┆ datetime[ ┆ ---       ┆   ┆ de        ┆ ude       ┆ ---       ┆ ---      │
│ datetime[ ┆ i64       ┆ μs]       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ bool     │
│ μs]       ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-01-1 ┆ 1043      ┆ 2025-01-1 ┆ 200149    ┆ … ┆ 51.511542 ┆ -0.056667 ┆ Watney    ┆ false    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ Street,   ┆          │
│ 23:59:00  ┆           ┆ 00:13:00  ┆           ┆   ┆           ┆           ┆ Shadwell  ┆          │
│ 2025-01-1 ┆ 300015    ┆ 2025-01-1 ┆ 300229    ┆ … ┆ 51.469202 ┆ -0.119022 ┆ Sidney    ┆ false    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ Road,     ┆          │
│ 23:59:00  ┆           ┆ 00:04:00  ┆           ┆   ┆           ┆           ┆ Stockwell ┆          │
│ 2025-01-1 ┆ 1068      ┆ 2025-01-1 ┆ 1051      ┆ … ┆ 51.534042 ┆ -0.086379 ┆ Shoreditc ┆ false    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ h Park,   ┆          │
│ 23:59:00  ┆           ┆ 00:10:00  ┆           ┆   ┆           ┆           ┆ Hoxton    ┆          │
│ 2025-01-1 ┆ 1159      ┆ 2025-01-1 ┆ 1007      ┆ … ┆ 51.51477  ┆ -0.122219 ┆ Drury     ┆ false    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ Lane,     ┆          │
│ 23:59:00  ┆           ┆ 00:10:00  ┆           ┆   ┆           ┆           ┆ Covent    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Garden    ┆          │
│ 2025-01-1 ┆ 200048    ┆ 2025-01-1 ┆ 1058      ┆ … ┆ 51.510212 ┆ 0.004979  ┆ Orchard   ┆ false    │
│ 4         ┆           ┆ 5         ┆           ┆   ┆           ┆           ┆ Place,    ┆          │
│ 23:58:00  ┆           ┆ 00:14:00  ┆           ┆   ┆           ┆           ┆ Blackwall ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Tunne…    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-12-1 ┆ 200141    ┆ 2025-12-1 ┆ 200237    ┆ … ┆ 51.472817 ┆ -0.199783 ┆ Parson's  ┆ false    │
│ 6         ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ Green ,   ┆          │
│ 00:02:00  ┆           ┆ 00:16:00  ┆           ┆   ┆           ┆           ┆ Parson's  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Gree…     ┆          │
│ 2025-12-1 ┆ 200011    ┆ 2025-12-1 ┆ 200250    ┆ … ┆ 51.520893 ┆ -0.051394 ┆ Cleveland ┆ false    │
│ 6         ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ Way,      ┆          │
│ 00:01:00  ┆           ┆ 00:16:00  ┆           ┆   ┆           ┆           ┆ Stepney   ┆          │
│ 2025-12-1 ┆ 300096    ┆ 2025-12-1 ┆ 962       ┆ … ┆ 51.505569 ┆ -0.111606 ┆ Stamford  ┆ false    │
│ 6         ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ Street,   ┆          │
│ 00:00:00  ┆           ┆ 00:07:00  ┆           ┆   ┆           ┆           ┆ South     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Bank      ┆          │
│ 2025-12-1 ┆ 3495      ┆ 2025-12-1 ┆ 300207    ┆ … ┆ 51.464995 ┆ -0.130908 ┆ Gauden    ┆ false    │
│ 6         ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ Road,     ┆          │
│ 00:00:00  ┆           ┆ 00:24:00  ┆           ┆   ┆           ┆           ┆ Clapham   ┆          │
│ 2025-12-1 ┆ 200185    ┆ 2025-12-1 ┆ 300013    ┆ … ┆ 51.474376 ┆ -0.155442 ┆ Austin    ┆ false    │
│ 6         ┆           ┆ 6         ┆           ┆   ┆           ┆           ┆ Road,     ┆          │
│ 00:00:00  ┆           ┆ 00:08:00  ┆           ┆   ┆           ┆           ┆ Battersea ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Park      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (820, 2)
┌─────────┬───────────────┐
│ station ┆ weekend_ratio │
│ ---     ┆ ---           │
│ i64     ┆ f64           │
╞═════════╪═══════════════╡
│ 300042  ┆ 0.239737      │
│ 1054    ┆ 0.199424      │
│ 200047  ┆ 0.2719        │
│ 300200  ┆ 0.35973       │
│ 300054  ┆ 0.25753       │
│ …       ┆ …             │
│ 200014  ┆ 0.327008      │
│ 200133  ┆ 0.26515       │
│ 200136  ┆ 0.143114      │
│ 1042    ┆ 0.201846      │
│ 1167    ┆ 0.109517      │
└─────────┴───────────────┘

In [55]:
#--------------------
#Rush hour features
#--------------------

df = df.with_columns([
    (
        (pl.col("hour") >= 7) &
        (pl.col("hour") <= 9)
    ).alias("morning_rush"),

    (
        (pl.col("hour") >= 17) &
        (pl.col("hour") <= 19)
    ).alias("evening_rush"),

    (
        (pl.col("hour") >= 0) &
        (pl.col("hour") <= 5)
    ).alias("night")
])

rush_profile = (
    df
    .group_by("start_station")
    .agg([
        pl.col("morning_rush").mean().alias("morning_rush_ratio"),
        pl.col("evening_rush").mean().alias("evening_rush_ratio"),
        pl.col("night").mean().alias("night_ratio"),
    ])
    .rename({"start_station": "station"})
)

rush_profile

shape: (820, 4)
┌─────────┬────────────────────┬────────────────────┬─────────────┐
│ station ┆ morning_rush_ratio ┆ evening_rush_ratio ┆ night_ratio │
│ ---     ┆ ---                ┆ ---                ┆ ---         │
│ i64     ┆ f64                ┆ f64                ┆ f64         │
╞═════════╪════════════════════╪════════════════════╪═════════════╡
│ 300060  ┆ 0.306729           ┆ 0.189456           ┆ 0.02856     │
│ 300042  ┆ 0.275862           ┆ 0.227217           ┆ 0.022373    │
│ 1069    ┆ 0.151697           ┆ 0.280297           ┆ 0.037639    │
│ 300072  ┆ 0.308251           ┆ 0.181848           ┆ 0.016667    │
│ 1057    ┆ 0.31608            ┆ 0.186008           ┆ 0.016706    │
│ …       ┆ …                  ┆ …                  ┆ …           │
│ 1167    ┆ 0.319267           ┆ 0.274001           ┆ 0.007213    │
│ 200148  ┆ 0.208458           ┆ 0.201137           ┆ 0.027079    │
│ 200008  ┆ 0.080437           ┆ 0.392508           ┆ 0.013632    │
│ 200145  ┆ 0.275596           ┆ 0.202665           ┆ 0.028986    │
│ 1027    ┆ 0.294814           ┆ 0.172877           ┆ 0.029456    │
└─────────┴────────────────────┴────────────────────┴─────────────┘

In [56]:
#-------------------
#Final df -> stations
#-------------------

stations = (
    stations
    #.join(hour_profile, on="station", how="left")
    .join(station_daily_avg, on="station", how="left")
    .join(weekend_profile, on="station", how="left")
    .join(rush_profile, on="station", how="left")
    .fill_null(0)
)

print(stations.shape)

(822, 16)

In [57]:
stations = stations.select(['station','n_departures','avg_daily_departures','n_arrivals','avg_daily_arrivals','departure_arrival_ratio','n_destinations','n_origins','mean_duration','median_duration','std_duration','weekend_ratio','morning_rush_ratio','evening_rush_ratio','night_ratio'])

stations

shape: (822, 15)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ station ┆ n_departur ┆ avg_daily ┆ n_arrival ┆ … ┆ weekend_r ┆ morning_r ┆ evening_r ┆ night_rat │
│ ---     ┆ es         ┆ _departur ┆ s         ┆   ┆ atio      ┆ ush_ratio ┆ ush_ratio ┆ io        │
│ i64     ┆ ---        ┆ es        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆ u32        ┆ ---       ┆ u32       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│         ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10632   ┆ 4058       ┆ 11.209945 ┆ 4031      ┆ … ┆ 0.174963  ┆ 0.126417  ┆ 0.245195  ┆ 0.014539  │
│ 22169   ┆ 11770      ┆ 32.335165 ┆ 11779     ┆ … ┆ 0.23237   ┆ 0.223874  ┆ 0.223959  ┆ 0.026423  │
│ 200053  ┆ 3280       ┆ 9.111111  ┆ 3097      ┆ … ┆ 0.21372   ┆ 0.217378  ┆ 0.283841  ┆ 0.031707  │
│ 300048  ┆ 7946       ┆ 22.383099 ┆ 7796      ┆ … ┆ 0.261515  ┆ 0.40813   ┆ 0.158067  ┆ 0.017871  │
│ 22175   ┆ 6259       ┆ 17.195055 ┆ 6160      ┆ … ┆ 0.281195  ┆ 0.275763  ┆ 0.150344  ┆ 0.044736  │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1045    ┆ 9855       ┆ 27.14876  ┆ 9912      ┆ … ┆ 0.121157  ┆ 0.149467  ┆ 0.41451   ┆ 0.017453  │
│ 1179    ┆ 7539       ┆ 20.654795 ┆ 7534      ┆ … ┆ 0.233055  ┆ 0.21024   ┆ 0.267277  ┆ 0.0256    │
│ 200157  ┆ 14369      ┆ 39.475275 ┆ 14398     ┆ … ┆ 0.314149  ┆ 0.065419  ┆ 0.308999  ┆ 0.022131  │
│ 200127  ┆ 4970       ┆ 13.653846 ┆ 5497      ┆ … ┆ 0.364789  ┆ 0.214085  ┆ 0.180885  ┆ 0.030181  │
│ 200154  ┆ 6182       ┆ 16.983516 ┆ 6308      ┆ … ┆ 0.308962  ┆ 0.197509  ┆ 0.245552  ┆ 0.028955  │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [59]:
#######################
#export df
#######################

stations.write_csv("../data/output/v2/4.stations_df.csv")